[package]
name = "rcards"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ctrlc = "3.4.5"
rustyline = "15.0.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tabled = "0.18.0"
